package minitwitter;

import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class UserView extends javax.swing.JFrame implements Element, Observer {

    /**
     * Creates new form UserView
     */
    User user;

    public UserView(User u) {
        initComponents();
        this.user = u;
        this.setTitle("User: " + user + "in group " + user.group);
        ArrayList<User> users = AdminControlPanel.getUsers();
        for (User user : users) {
            allUserList.addItem(user);
        }
        allUserList.removeItem(this.user);

        for (User user : user.followingUsers) {
            allUserList.removeItem(user);
        }

        ArrayList<UserGroup> userGroups = AdminControlPanel.userGroups;
        for (UserGroup ug : userGroups) {
            allGroupList.addItem(ug);
        }
        //init all the users list
        updateUserList();
        updateNewsFeed();
    }

    @Override
    public void accept(VisitorInterface visitor) {
        visitor.visitUser(this);
    }

    /**
     * Update method for observable object(following user) update
     *
     * @param followingUser
     * @param message
     */
    @Override
    public void update(Observable followingUser, Object message) {
        changeFollowingUserList(followingUser);
        updateNewsFeed(followingUser, message);
    }

    /**
     * change the following users
     */
    private void changeFollowingUserList(Observable followingUser) {

        user.followingUsers.add((User) followingUser);

    }

    /**
     * update news feed method
     * <u>news feed update</u>
     */
    public void updateNewsFeed(Observable followingUser, Object message) {
        //get followers news feed and update the feed

    }

    public void updateNewsFeed() {
        //get followers news feed and update the feed
        DefaultListModel defaultListModel = new DefaultListModel();
        for (User u : user.followingUsers) {
            for (String msg : u.myTweets) {
                defaultListModel.addElement(u + ": " + msg);
            }
        }

        newsFeedList.setModel(defaultListModel);

    }

    /**
     * updateUserList
     */
    private void updateUserList() {

        DefaultListModel defaultListModel = new DefaultListModel();
        for (User u : user.followingUsers) {
            defaultListModel.addElement(u);
        }

        followingUsersList.setModel(defaultListModel);
        //this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        followUserBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        followingUsersList = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        newTweetTextArea = new javax.swing.JTextArea();
        postTweetBtn = new javax.swing.JButton();
        allUserList = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        newsFeedList = new javax.swing.JList();
        allGroupList = new javax.swing.JComboBox();
        followGroupBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        followUserBtn.setText("Follow User");
        followUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                followUserBtnActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(followingUsersList);

        newTweetTextArea.setColumns(20);
        newTweetTextArea.setRows(5);
        jScrollPane3.setViewportView(newTweetTextArea);

        postTweetBtn.setText("Post Tweet");
        postTweetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postTweetBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("News Feed");

        jLabel2.setText("Current Following");

        jScrollPane4.setViewportView(newsFeedList);

        followGroupBtn.setText("Add to Group");
        followGroupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                followGroupBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(allUserList, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(74, 74, 74)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(followUserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                        .addComponent(postTweetBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jScrollPane2)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane4))
                            .addComponent(allGroupList, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(followGroupBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(followUserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(allUserList))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allGroupList, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(followGroupBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(postTweetBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * New tweet
     *
     * @param evt
     */
    private void postTweetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postTweetBtnActionPerformed
        String tweet = newTweetTextArea.getText();
        //notify followers to update the news feed
        user.tweet(tweet);
        user.notifyObservers();
        JOptionPane.showMessageDialog(rootPane, "New Tweet Added!\n Followers notified!");
        //update the followers
    }//GEN-LAST:event_postTweetBtnActionPerformed

    /**
     * follow a user: add that user to the observers list
     *
     * @param evt
     */
    private void followUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_followUserBtnActionPerformed
        User follower = (User) allUserList.getSelectedItem();
        //add this follower to the followers list of the user
        user.followingUsers.add(follower);
        //remove from the available users to folllow list
        allUserList.removeItem(follower);
        updateUserList();
        user.addObserver(follower);
        updateNewsFeed();
        JOptionPane.showMessageDialog(rootPane, "User: " + follower + " added to following users!");

    }//GEN-LAST:event_followUserBtnActionPerformed

    /**
     * Add user to a group
     *
     * @param evt
     */
    private void followGroupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_followGroupBtnActionPerformed

        UserGroup group = (UserGroup) allGroupList.getSelectedItem();
        user.group = group;
        group.users.add(user);
        JOptionPane.showMessageDialog(rootPane, "User is added to the Group: " + group);
    }//GEN-LAST:event_followGroupBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox allGroupList;
    private javax.swing.JComboBox allUserList;
    private javax.swing.JButton followGroupBtn;
    private javax.swing.JButton followUserBtn;
    private javax.swing.JList followingUsersList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea newTweetTextArea;
    private javax.swing.JList newsFeedList;
    private javax.swing.JButton postTweetBtn;
    // End of variables declaration//GEN-END:variables

}
