package minitwitter;

import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class UserView extends javax.swing.JFrame implements Element, Observer {

    /**
     * Creates new form UserView
     */
    User user;

    public UserView(User u) {
        initComponents();
        this.user = u;
        this.setTitle("User: " + user);
        ArrayList<User> users = AdminControlPanel.getUsers();
        for (User user : users) {
            allUserList.addItem(user);
        }
        allUserList.removeItem(this.user);

        for (User user : user.followingUsers) {
            allUserList.removeItem(user);
        }
        //init all the users list
        updateUserList();
    }

    @Override
    public void accept(VisitorInterface visitor) {
        visitor.visitUser(this);
    }

    /**
     * Update method for observable object(following user) update
     *
     * @param followingUser
     * @param message
     */
    @Override
    public void update(Observable followingUser, Object message) {
        changeFollowingUserList(followingUser);
        updateNewsFeed(followingUser, message);
    }

    /**
     * change the following users
     */
    private void changeFollowingUserList(Observable followingUser) {

        user.followingUsers.add((User) followingUser);

    }

    /**
     * update news feed method
     * <u>news feed update</u>
     */
    private void updateNewsFeed(Observable followingUser, Object message) {
        //get followers news feed and update the feed
        String s = newsFeedList.getText();
        s.concat(String.format("%s: %s", followingUser.toString(), message.toString()));
        newsFeedList.setText(s);
        System.out.println(s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        followUserBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        followingUsersList = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        newTweetTextArea = new javax.swing.JTextArea();
        postTweetBtn = new javax.swing.JButton();
        allUserList = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        newsFeedList = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        followUserBtn.setText("Follow User");
        followUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                followUserBtnActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(followingUsersList);

        newTweetTextArea.setColumns(20);
        newTweetTextArea.setRows(5);
        jScrollPane3.setViewportView(newTweetTextArea);

        postTweetBtn.setText("Post Tweet");
        postTweetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postTweetBtnActionPerformed(evt);
            }
        });

        newsFeedList.setColumns(20);
        newsFeedList.setRows(5);
        jScrollPane1.setViewportView(newsFeedList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(allUserList, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(followUserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                    .addComponent(postTweetBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(followUserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(allUserList))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(postTweetBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * New tweet
     *
     * @param evt
     */
    private void postTweetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postTweetBtnActionPerformed
        String tweet = newTweetTextArea.getText();
        //notify followers to update the news feed
        user.tweet(tweet);
        JOptionPane.showMessageDialog(rootPane, "New Tweet Added!\n Followers notified!");
        //update the followers
    }//GEN-LAST:event_postTweetBtnActionPerformed

    /**
     * follow a user: add that user to the observers list
     *
     * @param evt
     */
    private void followUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_followUserBtnActionPerformed
        User follower = (User) allUserList.getSelectedItem();
        //add this follower to the followers list of the user
        user.followingUsers.add(follower);
        //remove from the available users to folllow list
        allUserList.removeItem(follower);
        updateUserList();
        user.addObserver(follower);
        JOptionPane.showMessageDialog(rootPane, "User: " + follower + " added to following users!");
    }//GEN-LAST:event_followUserBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox allUserList;
    private javax.swing.JButton followUserBtn;
    private javax.swing.JList followingUsersList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea newTweetTextArea;
    private javax.swing.JTextArea newsFeedList;
    private javax.swing.JButton postTweetBtn;
    // End of variables declaration//GEN-END:variables

    private void updateUserList() {

        DefaultListModel defaultListModel = new DefaultListModel();
        for (User u : user.followingUsers) {
            defaultListModel.addElement(u);
        }

        followingUsersList.setModel(defaultListModel);
        //this.setVisible(true);
    }

}
